### ISSUE TITLE
Multiple owners is borked.

### ISSUE THREAD

**Issue by H3xadecimal** [HexadecimalPython/Xeili-DiscordBot#10]
ID does not register unless bot is rebooted.
~ID saves as int instead of string.~ Fixed in god knows which commit at this point.

**Comment by Pandentia** [comment]
and I thought *my* bugs were bad

**Comment by HexadecimalPython** [comment]
Here we can see who has the superior coding knowledge.

**Comment by Pandentia** [comment]
it's definitely you :^)

**Comment by HexadecimalPython** [comment]
*Totally* me.

**Comment by martmists** [comment]
Could y'all stop spamming my inbox thanks

**Comment by Pandentia** [comment]
no

**Comment by HexadecimalPython** [comment]
why the fuck are you using emails pand

**Comment by Pandentia** [comment]
because GitHub's mobile website is terrible and so are all related apps for
mobile

**Comment by Ovyerus** [comment]
Managed to fix the ids not being saving as strings, however a reboot is still needed for it to actually get updated.

**Comment by Ovyerus** [comment]
I think I know the issue.
When adding/removing an owner, it does update the database properly, which is why it works on a reboot, however it also only edits that one instance of dataIO, and the other instances don't reload (e.g. instance on bot class, and the ones for modules).

**Comment by HexadecimalPython** [comment]
Moved to #20
