### ISSUE TITLE
Multiple bugs regarding the command system.

### ISSUE THREAD

**Issue by H3xadecimal** [HexadecimalPython/Xeili-DiscordBot#14]
1. ~Cannot load modules in other directories.~ Fixed in 0a5b66d
2. ~Able to use subcommands without parent command.~ Fixed in 3db9cc0
3. Cannot directly use command arguments as variables*

*~Though that might be me not fully understanding the new command system.~
Proven to not be the case, Requires more time to be fixed.
This is caused due to the arguments being registered as strings instead of function variables.

Developers in charge of those issues please DM me on Discord for further details.

**Comment by HexadecimalPython** [comment]
Issue updated to match partial fixes.

**Comment by Ovyerus** [comment]
Argument handling added in 0d0a789
