### ISSUE TITLE
Bugs with CommandGroups

### ISSUE THREAD

**Issue by Ovyerus** [HexadecimalPython/Xeili-DiscordBot#16]
CommandGroups don't get added into the `CommandHolder.modules[module_name]` list.
Sometimes, a module will fail to load due to the following error, which appears to be caused by a CommandGroup.
```py
Traceback (most recent call last):
  File "/home/rslsync/OvyBot/amethyst.py", line 232, in on_message
    await self.holder.run_command(ctx)
  File "/home/rslsync/OvyBot/utils/command_system.py", line 522, in run_command
    await cmd.run(ctx)
  File "/home/rslsync/OvyBot/utils/command_system.py", line 187, in run
    await self.func(self.cls, ctx, *args, **kwargs)
  File "/home/rslsync/OvyBot/modules/core.py", line 65, in module
    self.amethyst.holder.load_module(module_name)
  File "/home/rslsync/OvyBot/utils/command_system.py", line 481, in load_module
    self.aliases[alias] = self.commands[cmd.name]
KeyError: 'nickname'
```

**Comment by martmists** [comment]
Why did we decide to move away from ext.commands again?

**Comment by HexadecimalPython** [comment]
Convenience purposes, also cause Ovy wanted to.

**Comment by Ovyerus** [comment]
Allows us to extend on it without too much hasse, and learning™

**Comment by martmists** [comment]
You can easily override the `command` class, which makes extending far easier. you could do something like 

```py
def command(*args, **kwargs):
    return discord.ext.commands.command(*args, cls=MyCommand, **kwargs)
```

**Comment by Ovyerus** [comment]
¯\\\_(ツ)_/¯

**Comment by Ovyerus** [comment]
Seems to be fixed.

**Comment by Ovyerus** [comment]
Key error bug still happening

**Comment by HexadecimalPython** [comment]
Further testing required to replicate this error on my end, Will also look into it.

**Comment by HexadecimalPython** [comment]
Error successfully replicated, not sure if that's a good thing.
Entering debugging phase.

**Comment by Ovyerus** [comment]
Latest commit *hopefully* fixed this.

**Comment by Ovyerus** [comment]
k nvm its not, but it seems to be happening less often.
