### ISSUE TITLE
Update 0.2: Call of The Wild.  

### ISSUE THREAD

**Issue by sr229** [HexadecimalPython/Xeili-DiscordBot#19]
- [ ] Fix remaining bugs. 
- [ ] Finish core commands. 
- [ ] Add monstercat music module.

**Comment by sr229** [comment]
CC @ClaraIO/amethyst

**Comment by HexadecimalPython** [comment]
Dang it, I said not to bug the German, he's vicious.

**Comment by sr229** [comment]
wait who's the german?

**Comment by HexadecimalPython** [comment]
Pand.

**Comment by sr229** [comment]
o shit vap

**Comment by HexadecimalPython** [comment]
Aight, who broke the fucking webhooks in Hound's server.

**Comment by sr229** [comment]
test

**Comment by sr229** [comment]
another test

**Comment by sr229** [comment]
why was I assigned 🤔

**Comment by HexadecimalPython** [comment]
you're also helping out with this, learn python™

**Comment by Pandentia** [comment]
[right, I can play this the hard way too](https://i.qcx.io/🔚🦍😔)

**Comment by Ovyerus** [comment]
🍿

**Comment by HexadecimalPython** [comment]
Change of plans, I'm taking care of the next update myself, Ya'll head back to base and wait for tasking.
