### ISSUE TITLE
Refactor base & modules.

### ISSUE THREAD

**Issue by H3xadecimal** [HexadecimalPython/Xeili-DiscordBot#27]
With the new database system in place, room was cleared for improvement, and being unhappy about the base of the bot, I've decided to refactor it, and move everything* that was in the json file to the database itself.

Optimization and completion of leftover code will be done

Modules* in Development is gonna be complete and ready to use /w more explanation later on.

Overall usability, reliability and management will be improved after this update.

**Comment by HexadecimalPython** [comment]
Update:
DataIO refactored in: de64d9d
Eval refactored in: 20c04cd

**Comment by HexadecimalPython** [comment]
`set avatar` seems to be broken, outputting the error code, likely caused by improper argument phasing.

**Comment by HexadecimalPython** [comment]
Update:
`set avatar` fixed in: b543d83 by @Ovyerus

**Comment by Ovyerus** [comment]
Update:
(Finally) moved `send_cmd_help` function into dusk: 5a806a8
