### ISSUE TITLE
Method defined outside of class

### ISSUE THREAD

**Issue by Martmists-GH** [HexadecimalPython/Xeili-DiscordBot#5]
[This](https://github.com/HexadecimalPython/Xeili/blob/developer_build/Xeili.py#L55) line suggests `send_cmd_help` exists in the current class, but it doesn't. instead, it's just under it outside the class. Either remove the `self.` or put `send_cmd_help` inside the class.

**Comment by HexadecimalPython** [comment]
`send_cmd_help` will be rewritten to properly fit the code.
